# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-14 15:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='班级')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '班级信息',
                'verbose_name_plural': '班级信息',
            },
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_num', models.CharField(max_length=30, verbose_name='学号')),
                ('student_phone', models.CharField(max_length=11, verbose_name='手机')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '学生详细信息',
                'verbose_name_plural': '学生详细信息',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='学生姓名')),
                ('age', models.IntegerField(default=18, verbose_name='学生年龄')),
                ('gender', models.CharField(choices=[('girl', '女'), ('boy', '男')], default='girl', max_length=10, verbose_name='性别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('banclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.BanClass', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='studentinfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.StudentInfo', verbose_name='所属学生'),
        ),
    ]
